# Generated by Django 3.2 on 2023-05-14 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ShoppingCart',
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-user',), 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
