version: '3.8'
services:

  db:
    image: postgres:14.4-alpine
    # container_name: postgresql
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: krisnovi/backend:v1.0.0
    restart: always
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    container_name: backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: krisnovi/frontend:v1.0.0
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/app/result_build/build/static/

  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
  
    depends_on:
      - backend

volumes:
  static_value:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: ext4
    #   device: /www/static/
  media_value:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: ext4
    #   device: /www/media/
  db_data:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: ext4
    #   device: /www/db/
# volumes:
#   db_data:
#   static_value:
#   madia_value: